// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('fbNotifier', ['ngGrid']).controller('NotifierCtrl', function($scope, $filter, notificationSvc) {
    var endOrContinue, logNotification, nextUser, notify;
    $scope.total = 0;
    $scope.users = "790128571\n100000882665737\n100000856290659\n100000354163834";
    $scope.notifications = [];
    $scope.grid = {
      data: 'notifications'
    };
    $scope.button = "Start!";
    $scope.startStopNotifications = function(form) {
      var users;
      if ($scope.button === "Start!" && form.$valid === true) {
        $scope.button = "Notifying... (PRESS AGAIN TO STOP)";
        users = $scope.users.split("\n");
        $scope.total = users.length;
        return notify(users);
      } else {
        if ($scope.button !== "Start!") {
          return $scope.button = "Stopping...";
        }
      }
    };
    logNotification = function(user, status) {
      return $scope.notifications.push({
        user: user,
        status: status,
        time: $filter('date')(Date.now(), "mediumTime")
      });
    };
    nextUser = function(users) {
      return users.shift();
    };
    endOrContinue = function(users) {
      if (users.length > 0 && $scope.button !== "Stopping...") {
        return notify(users);
      } else {
        return $scope.button = "Start!";
      }
    };
    return notify = function(users) {
      var user;
      user = nextUser(users);
      $scope.users = users.join("\n");
      return notificationSvc.notify($scope.appToken, user, $scope.url, $scope.text, $scope.ref).success(function(data) {
        logNotification(user, "OK");
        return endOrContinue(users);
      }).error(function(err) {
        logNotification(user, err.error != null ? err.error.message : "Unknown error - see browser console");
        return endOrContinue(users);
      });
    };
  }).service('notificationSvc', function($http) {
    return this.notify = function(token, user, url, text, ref) {
      if (ref == null) {
        ref = "";
      }
      text = text.replace('@USER', "@[" + user + "]");
      return $http.post("https://graph.facebook.com/" + user + "/notifications", null, {
        params: {
          access_token: token,
          template: text,
          href: url,
          ref: ref
        }
      });
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
